=== TKinga/F75CP6_XMLGyak/XMLTaskF75CP6/XMLSchemaF75CP6.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--Egyszerű típusok, saját típusok meghatározása-->


    <xs:element name="fajtak" type="xs:string"/>
    <xs:element name="leiras" type="xs:string"/>
    <xs:element name="ar" type="xs:integer"/>
    <xs:element name="datum" type="xs:date"/>
    <xs:element name="modja" type="xs:string"/>
    <xs:element name="szallitasi_koltseg" type="xs:integer"/>
    <xs:element name="megjegyzes" type="xs:string"/>
    <xs:element name="nev" type="xs:string"/>
    <xs:element name="telepules" type="xs:string"/>
    <xs:element name="utca" type="xs:string"/>
    <xs:element name="hazszam" type="xs:integer"/>
    <xs:element name="e-mail_cim" type="xs:string"/>
    <xs:element name="telefonszam" type="xs:integer"/>
    <xs:element name="minosites" type="minősítésTípus"/> 
    <xs:element name="nyitva" type="xs:string"/>   

    <xs:simpleType name="minősítésTípus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="5" />
        </xs:restriction>
    </xs:simpleType>


    
    <!--Összetett típusok meghatározása-->

    <xs:complexType name="termékekTípus" >
        <xs:sequence>
            <xs:element name="fajtak" type="xs:string"/>
            <xs:element name="leiras" type="xs:string"/>
            <xs:element ref="ar" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Term_ID" type="xs:integer"/>
        <xs:attribute name="Cukda_ID" type="xs:integer"/>
        <xs:attribute name="Cuk_ID" type="xs:integer"/>
        <xs:attribute name="Megr_ID" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="csomagTípus">
        <xs:sequence>
            <xs:element ref="datum" />
        </xs:sequence>
        <xs:attribute name="Term_ID" type="xs:integer"/>
        <xs:attribute name="Szall_ID" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="szállításTípus">
        <xs:sequence>
            <xs:element ref="modja" />
            <xs:element ref="szallitasi_koltseg" minOccurs="0" />
            <xs:element name="megjegyzes" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="Szall_ID" type="xs:integer"/>
    </xs:complexType>



    <xs:complexType name="megrendelőTípus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element name="cim">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="telepules" type="xs:string"/>
                        <xs:element name="utca" type="xs:string"/>
                        <xs:element name="hazszam" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element ref="telefonszam" maxOccurs="unbounded"/>
            <xs:element ref="e-mail_cim"/>
        </xs:sequence>
        <xs:attribute name="Megr_ID" type="xs:integer"/>
        <xs:attribute name="Szall_ID" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="cukrászTípus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element ref="minosites"/>
            <xs:element ref="e-mail_cim"/>
        </xs:sequence>
        <xs:attribute name="Cuk_ID" type="xs:integer"/>
        <xs:attribute name="Cukda_ID" type="xs:integer"/>
    </xs:complexType>



    <xs:complexType name="cukrászdaTípus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element ref="nyitva"/>
        </xs:sequence>
        <xs:attribute name="Cukda_ID" type="xs:integer"/>
        <xs:attribute name="Tul_ID" type="xs:integer"/>
    </xs:complexType>


    <xs:complexType name="tulajdonosTípus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element ref="telefonszam"/>
            <xs:element ref="e-mail_cim"/>
        </xs:sequence>
        <xs:attribute name="Tul_ID" type="xs:integer"/>
    </xs:complexType>        




<!--Gyökérelem meghatározása-->

<xs:element name="F75CP6_Cukraszda">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="termekek" type="termékekTípus" maxOccurs="unbounded"/>
            <xs:element name="csomag" type="csomagTípus" maxOccurs="unbounded"/>
            <xs:element name="szallitas" type="szállításTípus" maxOccurs="unbounded"/>
            <xs:element name="megrendelo" type="megrendelőTípus" maxOccurs="unbounded"/>
            <xs:element name="cukrasz" type="cukrászTípus" maxOccurs="unbounded"/>
            <xs:element name="cukraszda" type="cukrászdaTípus" maxOccurs="unbounded"/>
            <xs:element name="tulajdonos" type="tulajdonosTípus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



    <!--Elsődleges kulcsok-->

    <xs:key name="termekekPK">
        <xs:selector xpath="termekek"/>
        <xs:field xpath="@Term_ID"/>
    </xs:key>


    <xs:key name="szállításPK">
        <xs:selector xpath="szallitas"/>
        <xs:field xpath="@Szall_ID"/>
    </xs:key>


    <xs:key name="megrendelőPK">
        <xs:selector xpath="megrendelo"/>
        <xs:field xpath="@Megr_ID"/>
    </xs:key>


    <xs:key name="cukrászPK">
        <xs:selector xpath="cukrasz"/>
        <xs:field xpath="@Cuk_ID"/>
    </xs:key>


    <xs:key name="cukrászdaPK">
        <xs:selector xpath="cukraszda"/>
        <xs:field xpath="@Cukda_ID"/>           
    </xs:key>


    <xs:key name="tulajdonosPK">
        <xs:selector xpath="tulajdonos"/>
        <xs:field xpath="@Tul_ID"/>     
    </xs:key>


    <!-- Idegen kulcsok -->


    <xs:keyref name="cukrászdaTermékekFK" refer="cukrászdaPK">
        <xs:selector xpath="termekek"/>
        <xs:field xpath="@Cukda_ID"/>
    </xs:keyref>

    <xs:keyref name="cukrászTermékekFK" refer="cukrászPK">
        <xs:selector xpath="termekek"/>
        <xs:field xpath="@Cuk_ID"/>
    </xs:keyref>


    <xs:keyref name="megrendelőTermékekFK" refer="megrendelőPK">
        <xs:selector xpath="termekek"/>
        <xs:field xpath="@Megr_ID"/>
    </xs:keyref>


    <xs:keyref name="termékekCsomagFK" refer="termekekPK">
        <xs:selector xpath="csomag"/>
        <xs:field xpath="@Term_ID"/>
    </xs:keyref>


    <xs:keyref name="szállításCsomagFK" refer="szállításPK">
        <xs:selector xpath="csomag"/>
        <xs:field xpath="@Szall_ID"/>
    </xs:keyref>


    <xs:keyref name="szállításMegrendelőFK" refer="szállításPK">
        <xs:selector xpath="megrendelo"/>
        <xs:field xpath="@Szall_ID"/>
    </xs:keyref>

    
    <xs:keyref name="cukrászdaCukrászFK" refer="cukrászdaPK">
        <xs:selector xpath="cukrasz"/>
        <xs:field xpath="@Cukda_ID"/>
    </xs:keyref>


    <!-- 1:1 kapcsolat -->

    <xs:unique name="tulajdonosCukrászda" >
        <xs:selector xpath="cukraszda"/>
        <xs:field xpath="@Tul_ID"/>
    </xs:unique>

  </xs:element>
</xs:schema>

=== TKinga/F75CP6_XMLGyak/XMLTaskF75CP6/XMLF75CP6.xml
<?xml version="1.0" encoding="UTF-8"?>


<F75CP6_Cukraszda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="XMLSchemaF75CP6.xsd">

<!--- termekek -->

<termekek Term_ID="1" Cukda_ID="11" Cuk_ID="01" Megr_ID="101">
    <fajtak>Epres csokitorta</fajtak>
    <leiras>csokis piskóta, étcsokis-tejszínes krémmel, epervelővel</leiras>
    <ar>12000</ar>
</termekek>

<termekek Term_ID="2" Cukda_ID="12" Cuk_ID="02" Megr_ID="102">
    <fajtak>Ishler</fajtak>
    <leiras>linzer tészta erdeigyümölcsös dzsemmel</leiras>
    <ar>240</ar>
</termekek>

<termekek Term_ID="3" Cukda_ID="13" Cuk_ID="03" Megr_ID="103">
    <fajtak>Macaron</fajtak>
    <leiras>őrölt mandulából készült korongok sós karamellás krémmel töltve</leiras>
    <ar>300</ar>
</termekek>


<!--- Csomag -->

<csomag Term_ID="1" Szall_ID="901">
    <datum>2023-07-07</datum>
</csomag>

<csomag  Term_ID="2" Szall_ID="902">
    <datum>2023-08-02</datum>
</csomag>

<csomag  Term_ID="3" Szall_ID="903">
    <datum>2023-08-11</datum>
</csomag>


<!--- SZÁLLÍTÁS -->

<szallitas Szall_ID="901">
    <modja>Házhoz szállítás</modja>
    <szallitasi_koltseg>3250</szallitasi_koltseg>
    <megjegyzes>A csomag várhatóan 12:55 és 14:55 között érkezik meg.</megjegyzes>
</szallitas>

<szallitas Szall_ID="902">
    <modja>Személyes átvétel</modja>
    <szallitasi_koltseg>0</szallitasi_koltseg>
    <megjegyzes>Nyitvatartási időben bármikor átveheti termékét.</megjegyzes>
</szallitas>


<szallitas Szall_ID="903">
    <modja>Házhoz szállítás</modja>
    <szallitasi_koltseg>2700</szallitasi_koltseg>
    <megjegyzes>A csomag várhatóan 11:20 és 13:20 között érkezik meg.</megjegyzes>
</szallitas>


<!--- MEGRENDELŐ -->

<megrendelo Megr_ID="101" Szall_ID="901">
    <nev>Kis Béla</nev>
    <cim>
        <telepules>Edelény</telepules>
        <utca>Uitz Béla utca</utca>
        <hazszam>28</hazszam>
    </cim>
    <telefonszam>36403127492</telefonszam>
    <telefonszam>36805551232</telefonszam>
    <e-mail_cim>beluka33@citromail.hu</e-mail_cim>
</megrendelo>


<megrendelo Megr_ID="102" Szall_ID="902">
    <nev>Afonyi Dóra</nev>
    <cim>
        <telepules>Kakucs</telepules>
        <utca>Arany János utca</utca>
        <hazszam>4</hazszam>
    </cim>
    <telefonszam>36803978912</telefonszam>
    <telefonszam>36408869769</telefonszam>
    <e-mail_cim>dora12@gmail.com</e-mail_cim>
</megrendelo>


<megrendelo Megr_ID="103" Szall_ID="903">
    <nev>Stoll Barbara</nev>
    <cim>
        <telepules>Veresegyház</telepules>
        <utca>Petőfi utca</utca>
        <hazszam>48</hazszam>
    </cim>
    <telefonszam>36807958169</telefonszam>
    <e-mail_cim>rebarbara18@gmail.com</e-mail_cim>
</megrendelo>



<!--- CUKRÁSZ -->

<cukrasz Cuk_ID="01" Cukda_ID="11">
    <nev>Réfi Réka</nev>
    <minosites>2</minosites>
    <e-mail_cim>rekuci15@gmail.com</e-mail_cim>
</cukrasz>

<cukrasz Cuk_ID="02" Cukda_ID="12">
    <nev>Túró Rudolf</nev>
    <minosites>3</minosites>
    <e-mail_cim>turorudi11@gmail.com</e-mail_cim>
</cukrasz>

<cukrasz Cuk_ID="03" Cukda_ID="13">
    <nev>Kerepesi Rebeka</nev>
    <minosites>5</minosites>
    <e-mail_cim>rebekabeka36@gmail.com</e-mail_cim>
</cukrasz>



<!--- CUKRÁSZDA -->

<cukraszda Cukda_ID="11" Tul_ID="001">
    <nev>Hajnali Álom</nev>
    <nyitva>8-16</nyitva>
</cukraszda>


<cukraszda Cukda_ID="12" Tul_ID="002">
    <nev>Éjféli Kívánság</nev>
    <nyitva>8-20</nyitva>
</cukraszda>


<cukraszda Cukda_ID="13" Tul_ID="003">
    <nev>Napsütéses Virágoskert</nev>
    <nyitva>10-22</nyitva>
</cukraszda>


<!--- TULAJDONOS -->

<tulajdonos Tul_ID="001">
    <nev>Tompa János</nev>
    <telefonszam>36803974892</telefonszam>
    <e-mail_cim>tmpjni56@gmail.com</e-mail_cim>
</tulajdonos>


<tulajdonos Tul_ID="002">
    <nev>Mészáros Mária</nev>
    <telefonszam>36904258798</telefonszam>
    <e-mail_cim>marikameszaros55@freemail.hu</e-mail_cim>
</tulajdonos>


<tulajdonos Tul_ID="003">
    <nev>Várkonyi Erika</nev>
    <telefonszam>36503459678</telefonszam>
    <e-mail_cim>varkonyierika16@gmail.com</e-mail_cim>
</tulajdonos>



</F75CP6_Cukraszda>
